domjudge:
    resource: '@DOMJudgeBundle/Controller/'
    type: annotation
    prefix: /

logout:
    path: /logout

overriden_routes:
    resource: "@DOMJudgeBundle/Resources/config/routing.yml"

fallback:
    path: /{path}
    defaults: { _controller: "legacy.controller.fallback:fallback" }
    requirements:
        path: .*

legacy_routes:
    resource: "@LegacyBundle/Resources/config/routing.yml"
